# =============================================================================
# scripts/08_cyp2d6_aims.R
#
# Purpose : Test whether the CYP2D6/CYP2D7 gene cluster on chr22 shows
#           elevated AFR-EUR Fst in our common-variant panel - probing
#           the project's clinical claim with its own data.
# =============================================================================

library(tidyverse)

BASE_DIR <- "/Users/tim/bioinformatics-portfolio/01-african-genomics"


# Gene coordinates (GRCh38) -----------------------------------------------
#
# IMPORTANT: use GRCh38 only. GRCh37 puts CYP2D6 at ~42.52Mb - wrong here.
# CYP2D6 verified via UCSC MANE Select track; CYP2D7 via HUGO HGNC.
# Both genes transcribe on the MINUS strand (higher coord = transcription start).

cyp2d6_start <- 42126499   # MANE Select: chr22:42126499-42130810
cyp2d6_end   <- 42130810

cyp2d7_start <- 42140203   # HUGO HGNC: chr22:42140203-42149500
cyp2d7_end   <- 42149500   # broader than GENCODE primary transcript (42144577)
# HUGO preferred - captures all annotated transcripts


# Load AFR-EUR Fst --------------------------------------------------------
# One row per chr22 variant; WC_FST = Weir & Cockerham Fst, AFR vs EUR.
# Generated by PLINK2 --fst method=wc in script 03.

fst_afr_eur <- read_tsv(
  file.path(BASE_DIR, "results/chr22_fst.AFR.EUR.fst.var"),
  show_col_types = FALSE
)
# Confirm column names match - PLINK2 naming can shift between versions
# Expected: "#CHROM" "POS" "ID" "OBS_CT" "WC_FST"
colnames(fst_afr_eur)


# Section 1: Narrow window (10kb either side of CYP2D6) ------------------
# Buffer accounts for LD - a causal variant can sit slightly outside a
# gene's boundaries but still be correlated with variants inside it.

buffer_narrow <- 10000

cyp2d6_variants <- fst_afr_eur %>%
  filter(POS >= cyp2d6_start - buffer_narrow,
         POS <= cyp2d6_end   + buffer_narrow) %>%
  arrange(desc(WC_FST))

cat("Variants in 10kb CYP2D6 window:", nrow(cyp2d6_variants), "\n")  # 1
print(cyp2d6_variants)

# The single hit (42122508, Fst=0.156) was checked at UCSC - it sits in
# NDUFA6-DT, a mitochondrial gene unrelated to CYP2D6. Dense genomic
# regions require browser verification; coordinate proximity ≠ relevance.

cat("Genome-wide chr22 mean Fst:", round(mean(fst_afr_eur$WC_FST, na.rm = TRUE), 4), "\n")
cat("10kb window mean Fst:      ", round(mean(cyp2d6_variants$WC_FST, na.rm = TRUE), 4), "\n")


# Section 2: Sparsity check -----------------------------------------------
# Is finding only 1 SNP suspicious? Calculate expected count at the
# dataset's average SNP density to distinguish biological signal from
# normal panel sparsity.

chr22_length     <- 50818468   # GRCh38 chr22 total length (bp)
n_total_variants <- 5141       # SNPs remaining after LD pruning

avg_spacing       <- chr22_length / n_total_variants
window_size       <- (cyp2d6_end + buffer_narrow) - (cyp2d6_start - buffer_narrow)
expected_variants <- window_size / avg_spacing

cat("Average SNP spacing:", round(avg_spacing), "bp\n")     # 9,885 bp
cat("Window size:        ", window_size, "bp\n")            # 24,311 bp
cat("Expected SNPs:      ", round(expected_variants, 2), "\n")  # 2.46
cat("Observed SNPs:      ", nrow(cyp2d6_variants), "\n")    # 1

# Finding 1 vs expected ~2.5 is normal sampling variation - not an error.
# Absence of CYP2D6 internal SNPs reflects LD pruning, not a failed filter:
# functional CYP2D6 variants are correlated with flanking common SNPs and
# were removed as "redundant" by --indep-pairwise. This is the expected
# behaviour of a pipeline designed for population structure, not pharmacogenomics.


# Section 3: Wider 50kb window --------------------------------------------
# Captures the whole CYP2D6/CYP2D7/CYP2D8 cluster. 50kb is standard for
# regional Fst analyses because human LD blocks typically extend 10-100kb.

buffer_wide <- 50000

region_wide <- fst_afr_eur %>%
  filter(POS >= cyp2d6_start - buffer_wide,
         POS <= cyp2d6_end   + buffer_wide) %>%
  arrange(desc(WC_FST))

cat("\nVariants in 50kb window:", nrow(region_wide), "\n")   # 11
cat("50kb window mean Fst:   ", round(mean(region_wide$WC_FST, na.rm = TRUE), 4), "\n")  # 0.1353
cat("Genome-wide chr22 mean: ", round(mean(fst_afr_eur$WC_FST, na.rm = TRUE), 4), "\n") # 0.0977

# Region is 38% above genome-wide background.
# Note: signal is patchy - three SNPs near 42,150,000 have near-zero Fst.
# This is expected: Fst tracks local LD structure, not distance uniformly.

print(region_wide)


# Section 4: Confirm top hit inside CYP2D7 --------------------------------
# Top hit (42142019, Fst=0.461) was verified at UCSC: chr22:42,135,000-42,150,000.
# Falls 1,816 bp into CYP2D7's gene body (42142019 - 42140203 = 1,816 bp).
#
# CYP2D7 is clinically relevant to CYP2D6: it shares ~92-98% sequence
# identity and generates CYP2D6 hybrid alleles (e.g. *13, *36) through
# gene conversion. Structural rearrangements between the two also create
# CYP2D6*5 (gene deletion, poor metabolizer) and gene duplications
# (ultrarapid metabolizer). Population-differentiated variation in CYP2D7
# is therefore plausibly linked to CYP2D6 functional diversity.

cyp2d7_hits <- region_wide %>%
  filter(POS >= cyp2d7_start, POS <= cyp2d7_end)

cat("\nVariants inside CYP2D7 (HUGO boundaries):", nrow(cyp2d7_hits), "\n")
print(cyp2d7_hits)
# Expected: 3 variants including top hit at Fst=0.461


# Section 5: Permutation test ---------------------------------------------
# Is the 50kb window mean (0.1353) unusual vs random chr22 windows?
# Draw 1,000 random sets of 11 SNPs from chr22; record each mean.
# Empirical p-value = fraction of random draws >= observed mean.
#
# Differs from script 05's bootstrap: bootstrap tests stability of an
# estimate; permutation tests whether a value is unusual vs background.

set.seed(42)   # reproducibility

n_perm   <- 1000
window_n <- nrow(region_wide)   # 11

perm_means <- replicate(n_perm, {
  mean(sample(fst_afr_eur$WC_FST, size = window_n, replace = FALSE),
       na.rm = TRUE)
})

observed_mean <- mean(region_wide$WC_FST, na.rm = TRUE)
p_value       <- mean(perm_means >= observed_mean)

cat("\nObserved mean Fst:", round(observed_mean, 4), "\n")   # 0.1353
cat("Empirical p-value:", round(p_value, 4), "\n")          # 0.168

# p=0.168: suggestive but underpowered at n=11 SNPs.
# Interpret as: "elevation is in the upper tail but not statistically
# significant at this sample size" - NOT as "no signal present."
# A denser panel (without LD pruning) would recover the full picture.


# Section 6: Plot - Regional Fst scatter with gene boundaries ------------

window_plot  <- 100000   # 100kb for plotting context

regional_plot <- fst_afr_eur %>%
  filter(POS >= cyp2d6_start - window_plot,
         POS <= cyp2d6_end   + window_plot)

# Y positions for gene labels - staggered to prevent overlap
# (CYP2D6 and CYP2D7 are only ~13kb apart on a 200kb plot window)
y_max   <- max(regional_plot$WC_FST, na.rm = TRUE)
y_cyp2d6_label <- y_max * 0.80
y_cyp2d7_label <- y_max * 0.95

p_cyp2d6 <- ggplot(regional_plot, aes(x = POS, y = WC_FST)) +
  
  geom_point(alpha = 0.6, color = "#D4600A", size = 2) +
  
  # Gene boundary bands - annotate() draws fixed shapes at specified
  # coordinates, independent of the data
  annotate("rect",
           xmin = cyp2d6_start, xmax = cyp2d6_end,
           ymin = -Inf, ymax = Inf,
           alpha = 0.15, fill = "#1A3A5C") +
  
  annotate("rect",
           xmin = cyp2d7_start, xmax = cyp2d7_end,
           ymin = -Inf, ymax = Inf,
           alpha = 0.20, fill = "#D4600A") +
  
  # Genome-wide mean as reference baseline
  geom_hline(yintercept = mean(fst_afr_eur$WC_FST, na.rm = TRUE),
             linetype = "dashed", color = "grey40", linewidth = 0.7) +
  
  # Gene labels - staggered y positions prevent overlap
  annotate("text",
           x = (cyp2d6_start + cyp2d6_end) / 2,
           y = y_cyp2d6_label,
           label = "CYP2D6", color = "#1A3A5C",
           size = 3.5, fontface = "bold") +
  
  annotate("text",
           x = (cyp2d7_start + cyp2d7_end) / 2,
           y = y_cyp2d7_label,
           label = "CYP2D7", color = "#D4600A",
           size = 3.5, fontface = "bold") +
  
  scale_x_continuous(labels = scales::comma) +
  
  labs(
    title    = "AFR vs EUR Fst around the CYP2D6/CYP2D7 gene cluster (chr22)",
    subtitle = sprintf(
      "50kb window mean Fst = %.4f vs chr22 genome-wide mean = %.4f (empirical p = %.3f)",
      observed_mean,
      mean(fst_afr_eur$WC_FST, na.rm = TRUE),
      p_value
    ),
    x       = "Position on chromosome 22 (bp)",
    y       = "Fst (Weir & Cockerham, AFR vs EUR)",
    caption = paste0(
      "Blue = CYP2D6 (GRCh38:42126499-42130810). ",
      "Orange = CYP2D7 (GRCh38:42140203-42149500, HUGO). ",
      "Dashed = chr22 genome-wide mean. ",
      "Top hit Fst=0.461 confirmed in CYP2D7 via UCSC."
    )
  ) +
  
  theme_classic(base_size = 14) +
  theme(
    plot.title    = element_text(face = "bold"),
    plot.subtitle = element_text(size = 10, color = "grey40"),
    plot.caption  = element_text(size = 8,  color = "grey50")
  )

ggsave(file.path(BASE_DIR, "results/figures/cyp2d6_fst_region.png"),
       p_cyp2d6, width = 11, height = 6, dpi = 300)
print(p_cyp2d6)


# Section 7: Plot - Permutation distribution ------------------------------

p_perm <- ggplot(data.frame(mean_fst = perm_means), aes(x = mean_fst)) +
  
  geom_histogram(bins = 40, fill = "#1A3A5C", alpha = 0.7) +
  
  geom_vline(xintercept = observed_mean,
             color = "#D4600A", linewidth = 1.2) +
  
  annotate("text",
           x = observed_mean + 0.001, y = 80,
           label = sprintf("Observed\n%.4f", observed_mean),
           color = "#D4600A", hjust = 0,
           size = 3.5, fontface = "bold") +
  
  labs(
    title    = "Permutation test: CYP2D6-region Fst vs random chr22 windows",
    subtitle = sprintf("1,000 random draws of %d SNPs; empirical p = %.4f",
                       window_n, p_value),
    x       = "Mean Fst of random 11-SNP draw",
    y       = "Count",
    caption = "Orange line = observed mean Fst in 50kb CYP2D6/CYP2D7 window"
  ) +
  
  theme_classic(base_size = 14) +
  theme(plot.title = element_text(face = "bold"))

ggsave(file.path(BASE_DIR, "results/figures/cyp2d6_permutation_test.png"),
       p_perm, width = 9, height = 6, dpi = 300)
print(p_perm)


# Results summary ---------------------------------------------------------
cat("\n=== KEY RESULTS ===\n")
cat("Top hit:        chr22:42142019:G:A inside CYP2D7\n")
cat("Top hit Fst:    0.461 (4.7x genome-wide mean of", round(mean(fst_afr_eur$WC_FST, na.rm=TRUE),4), ")\n")
cat("50kb mean Fst:  ", round(observed_mean, 4), "\n")
cat("Empirical p:    ", round(p_value, 4), "(underpowered at n=11, not negative)\n")
cat("NDUFA6-DT SNP:  42122508 - unrelated gene, excluded from interpretation\n")
cat("Pipeline note:  MAF+LD-pruning removes functional CYP2D6 variants by design\n")
cat("                Full pharmacogenomics analysis requires separate pipeline\n")